language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"

# sudo: false  # Use container-based infrastructure

before_install:
  # http://conda.pydata.org/docs/travis.html
  - sudo apt-get update
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
# command to install dependencies
install:
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy astropy matplotlib
  - source activate test-environment
  - pip install -r requirements.txt
  - python setup.py install
  - pip install pytest pytest-cov hypothesis

# command to run tests
script:
    py.test --cov=eniric --cov-report=term
    # coverage run --source eniric -m py.test
    # coverage report
