# Default YAML configuration script for Eniric

# Paths to locations used by eniric
# Paths can either be strings of list of strings which will be passed
# to os.path.join() [os independent]
paths:
  phoenix_raw: [] # Path to Phoenix-ACES spectra
  btsettl_raw: [] # Path to BT-Settl spectra
  test_data: ["..","data","test_data"]
  atmmodel: ["..","data", "atmmodel"]
  precision: ["precision"]  # A place to put precision results
  # Obsolete paths for testing only
  phoenix_dat: ["data", "test_data","obsolete","PHOENIX-ACES_spectra"]
  results:  ["..","data","test_data","obsolete","results"]
  resampled: ["..","data","test_data","obsolete", "resampled"]

# Wavelength bands.
bands:
  all: ["VIS", "GAP", "Z", "Y", "J", "H", "K", "CONT", "NIR", "TEST"]
# Already included wavelength bands  (see `eniric.utilities.py`)
# "VIS": (0.38, 0.78),
# "GAP": (0.78, 0.83),
# "Z": (0.83, 0.93),
# "Y": (1.0, 1.1),
# "J": (1.17, 1.33),
# "H": (1.5, 1.75),
# "K": (2.07, 2.35),
# "CONT": (0.45, 1.05),
# "NIR": (0.83, 2.35)

# Add your custom band limits here and include in "all" above
custom_bands:
  TEST: (2.1, 2.2)

cache:
  # location: None  # Disables cache
  location: [".joblib"]

atmmodel:
  # Base name of telluric model
  base: "Average_TAPAS_2014"


## Starfish Keywords
# These keywords are necessary to exist in the config.yaml (to enable Starfish to run)
# but are not used by and have no affect on Eniric and the loading of the phoenix spectral libraries.
# As such they are all set to nothing.
#
# To configure the path to the phoenix libraries use
#    paths:
#        phoenix_raw:
#        btsettl_raw:
# above.
# If you are wanting to use "Eniric" with the other features "Starfish" good luck!
# (or open an issue github issue).
name: ""
outdir: ""
plotdir: ""
grid:
  raw_path: ""
  hdf5_path: ""
  key_name: ""
  parname: []
  parrange: []
  wl_range: []
  buffer: 0
data:
  grid_name: ""
  instruments: []
